import os
import pathlib
import sys
from typing import List, Optional, Tuple

from .config import get_build_dir
from .registry import get_registry


_SHELL_INIT_TEMPLATE = r"""# heppyyier shell integration — generated by `heppyyier shell-init`
# Add to ~/.bashrc or ~/.zshrc:  eval "$(heppyyier shell-init)"

module() {
  local action="$1"
  local pkg="$2"
  local name="${pkg%%/*}"
  local version="${pkg#*/}"
  [ "$version" = "$name" ] && version=""

  case "$action" in
    load)
      local env_path
      env_path="$(heppyyier _shell-env-path "$name" $version 2>/dev/null)" || {
        echo "heppyyier: package '$pkg' not found" >&2
        return 1
      }
      # shellcheck disable=SC1090
      source "$env_path/env.sh"
      ;;
    unload)
      local env_path
      env_path="$(heppyyier _shell-env-path "$name" $version 2>/dev/null)" || {
        echo "heppyyier: package '$pkg' not found" >&2
        return 1
      }
      # shellcheck disable=SC1090
      source "$env_path/env-unset.sh"
      ;;
    list)
      heppyyier _shell-list
      ;;
    avail)
      heppyyier avail
      ;;
    *)
      echo "Usage: module {load|unload|list|avail} [package[/version]]" >&2
      return 1
      ;;
  esac
}
"""

_ENV_SH_TEMPLATE = """\
# heppyyier env — {name} {version}
export {NAME}_DIR="{prefix}"
export PATH="{prefix}/bin:$PATH"
{lib_path_line}
export CPATH="{prefix}/include:$CPATH"
export HEPPYYIER_LOADED_{NAME}="{version}"
export HEPPYYIER_LOADED_{NAME}_PREFIX="{prefix}"
"""

_ENV_UNSET_SH_TEMPLATE = (
    "# heppyyier env-unset — {name} {version}\n"
    'export PATH="${{PATH//{prefix_escaped_bin}:/}}"\n'
    "{lib_unset_line}\n"
    'export CPATH="${{CPATH//{prefix_escaped_inc}:/}}"\n'
    "unset {NAME}_DIR\n"
    "unset HEPPYYIER_LOADED_{NAME}\n"
    "unset HEPPYYIER_LOADED_{NAME}_PREFIX\n"
)


def shell_init_script() -> str:
    return _SHELL_INIT_TEMPLATE


def get_modulefiles_dir() -> pathlib.Path:
    return get_build_dir() / "modulefiles"


def write_tcl_modulefile(name: str, version: str, prefix: pathlib.Path) -> pathlib.Path:
    """Generate a TCL modulefile for use with Environment Modules / Lmod."""
    NAME = name.upper().replace("-", "_")
    p = prefix
    lines = [
        "#%Module1.0",
        f"## {name}/{version} — generated by heppyyier",
        "",
        f'module-whatis "{name} {version}"',
        "",
        f"set prefix {p}",
        "",
        f"setenv {NAME}_DIR $prefix",
        f"setenv {NAME}_VERSION {version}",
    ]
    if (p / "bin").is_dir():
        lines.append("prepend-path PATH $prefix/bin")
    if (p / "lib").is_dir():
        lines.append("prepend-path LD_LIBRARY_PATH $prefix/lib")
        lines.append("prepend-path DYLD_LIBRARY_PATH $prefix/lib")
    if (p / "include").is_dir():
        lines.append("prepend-path CPATH $prefix/include")
    content = "\n".join(lines) + "\n"

    mod_dir = get_modulefiles_dir() / name
    mod_dir.mkdir(parents=True, exist_ok=True)
    mod_file = mod_dir / version
    mod_file.write_text(content)
    return mod_file


def generate_env_scripts(name: str, version: str, prefix: pathlib.Path) -> None:
    NAME = name.upper().replace("-", "_")
    prefix_str = str(prefix)
    prefix_escaped = prefix_str.replace("/", "\\/")

    lib_dir = f"{prefix_str}/lib"
    bin_dir = f"{prefix_str}/bin"
    inc_dir = f"{prefix_str}/include"
    lib_dir_escaped = lib_dir.replace("/", "\\/")
    bin_dir_escaped = bin_dir.replace("/", "\\/")
    inc_dir_escaped = inc_dir.replace("/", "\\/")

    if sys.platform == "darwin":
        lib_var = "DYLD_LIBRARY_PATH"
    else:
        lib_var = "LD_LIBRARY_PATH"

    lib_path_line = f'export {lib_var}="{lib_dir}:${lib_var}"'
    lib_unset_line = f'export {lib_var}="${{{lib_var}//{lib_dir_escaped}:/}}"'

    env_sh = _ENV_SH_TEMPLATE.format(
        name=name,
        NAME=NAME,
        version=version,
        prefix=prefix_str,
        lib_path_line=lib_path_line,
    )
    env_unset_sh = _ENV_UNSET_SH_TEMPLATE.format(
        name=name,
        NAME=NAME,
        version=version,
        prefix=prefix_str,
        prefix_escaped_bin=bin_dir_escaped,
        prefix_escaped_inc=inc_dir_escaped,
        lib_unset_line=lib_unset_line,
    )

    (prefix / "env.sh").write_text(env_sh)
    (prefix / "env-unset.sh").write_text(env_unset_sh)


def env_path(name: str, version: Optional[str] = None) -> pathlib.Path:
    reg = get_registry()
    record = reg.get(name)
    if record is None:
        from .exceptions import PackageNotInstalledError
        raise PackageNotInstalledError(
            f"Package '{name}' is not installed. Run: heppyyier install {name}"
        )
    if version and record.get("version") != version:
        # Try to find that version directly in build dir
        candidate = get_build_dir() / name / version
        if (candidate / "env.sh").exists():
            return candidate
        from .exceptions import PackageNotInstalledError
        raise PackageNotInstalledError(
            f"Package '{name}' version '{version}' not found. "
            f"Installed: {record.get('version')}"
        )
    return pathlib.Path(record["prefix"])


def list_loaded() -> List[Tuple[str, str]]:
    results = []
    for key, value in os.environ.items():
        if key.startswith("HEPPYYIER_LOADED_") and not key.endswith("_PREFIX"):
            name = key[len("HEPPYYIER_LOADED_"):].lower().replace("_", "-")
            results.append((name, value))
    return results
